# Generated by Django 4.2.4 on 2023-08-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('numero_documento', models.CharField(max_length=20)),
                ('tipo_documento', models.CharField(max_length=20)),
                ('numero_ficha', models.CharField(max_length=20)),
            ],
        ),
    ]
